### ISSUE TITLE
Add .readme file that explains the configuration

### ISSUE THREAD

**Issue by antipainK** [Maufeat/VoliBot#4]
I tried to run the CMake project that you provided, but it's not working and reporting bugs.
I would like to see how you configured it and whether you used some tools, that you didn't specify in it.

![obraz](https://user-images.githubusercontent.com/45923220/93084264-1409ca00-f694-11ea-9676-05bbcfc34f67.png)

**Comment by Maufeat** [comment]
![grafik](https://user-images.githubusercontent.com/3602392/93108248-dd8f7780-f6b2-11ea-8f7e-43d72b4e0e4f.png)
